config/routes.rb
Rails.application.routes.draw do

	root "bar#index"
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
  resources :bars do
    resources :reviews
    resources :reservations
   end
end

app/models/bar.rb
class Bar < ActiveRecord::Base

	# has_many :reviews
 #  has_many :users, :through => :reservations, :reviews
 #  has_many :reservations


	validates :name, :description, :address, :capacity, :presence => true
	validates :capacity, :numericality => {:only_integer => true}

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :bar, :user
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = 'Please log in'
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user
  
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  
  def index
    @bars = Bar.all
  end

  def show
    @bar = Bar.find(params[:id])


    if current_user
      @reservation = @bar.reservation.build
    end
  end

  def new
    @bar = Bar.new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def create
    @bar = Bar.new(bar_params)

    if @bar.save
      redirect_to bars_url
    else
      render :new
    end

  end

  def update
    @bar = Bar.find(params[:id])

    if @bar.update_attributes(bar_params)
      redirect_to bars_path(@bar)
    else 
      render :edit
    end 
  end

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    rediret_to bars_path
  end

  private
  def bar_params
    params.require(:bar).permit(:name, :address, :latitute, :longitude, :capacity, :description, :user_id, :category)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_bar

  def create
    @reservation = @bar.reservations.new(reservation_params)
    @reservation.user_id = current_user.id

    if @reservation.save
      redirect_to bars_path, notice: 'Reservation created successfully'
    else
      render 'bars'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @bar = @reservation.bar

    if 
      raise AuthenticationError
  end
end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
  end

  def load_bar
    @bar = Bar.find(params[:bar_id])
  end
  
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user
			session[:user_id] = user.id
			redirect_to root_path, notice: 'Successfully signed in'
		else
			flash[:alert] = 'Log in credentials incorrect'
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			flash.now['error']
			render :new
		end
	end

	def update
		@user = User.find(params[:id])
	end

	def show
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV['SEGMENT_IO_KEY'] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load('<%= ENV['SEGMENT_IO_KEY'] %>');
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render 'analytics' %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>

	<% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
   <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/create.html.erb
<h1>Bars#create</h1>
<p>Find me in app/views/bars/create.html.erb</p>

app/views/bars/destroy.html.erb
<h1>Bars#destroy</h1>
<p>Find me in app/views/bars/destroy.html.erb</p>

app/views/bars/edit.html.erb
<h1>Bars#edit</h1>
<p>Find me in app/views/bars/edit.html.erb</p>

app/views/bars/index.html.erb
<h1>Bars</h1>
<% @bars.each do |bar| %>
  <p><%= bar[:name] %> - $<%= bar.address %> 
    <%= link_to "Show", "/bars/#{bar.id}" %> 
  </p>
<% end %>

app/views/bars/new.html.erb
<h1> New Bar </h1>
<%= render 'form' %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<h1>Bar Information</h1><br/>
<h3><%=@bar.name%> - $<%=@bar.address%> </h3>
	<p>Capacity:<%= @bar.capacity %></p>
	<p>Description:<%= @bar.description %></p>


	<h4>Reservation</h4>

  <%= form_for([@bar, @reservation]) do |f| %>
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :start_time %><br />
      <%= f.datetime_field :start_time %>
    </div>
    <div class="field">
    	<%= f.label :capacity %><br />
    	<%= f.number_field :capacity %><br />
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/bars/update.html.erb
<h1>Bars#update</h1>
<p>Find me in app/views/bars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'flashes' -%>

	



  <%= yield %>

		<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end %>
	</p>


  <%= render 'javascript' %>
</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/review/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/review/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/review/edit.html.erb
<h1>Review#edit</h1>
<p>Find me in app/views/review/edit.html.erb</p>

app/views/review/new.html.erb
<h1>Review#new</h1>
<p>Find me in app/views/review/new.html.erb</p>

app/views/review/update.html.erb
<h1>Review#update</h1>
<p>Find me in app/views/review/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>

	<% if @user.errors.any? %>
		<div class = "error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

		<div class="field">
			<%= f.label :name %><br/>
			<%= f.text_field :name%>
		</div>
		<div class="field">
			<%= f.label :email %><br/>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %></br>
			<%= f.password_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation %><br/>
			<%= f.password_field :password_confirmation %>
		</div>
		<div class="actions"><%= f.submit %></div>
	<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>